apiVersion: v1
kind: Service
metadata:
  name: springappsvc
  namespace: mss-warmart-prod
spec:
  type: NodePort
  selector:
    app: springapp
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30005
---
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: mss-warmart-prod
spec:
  clusterIP: None
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongo
